### ISSUE TITLE
ConsoleForm_FormClosed

### ISSUE THREAD

**Issue by SaloEater** [Akharote1/RazorIDE#2]
I get this error when i trying to close console window.
Razor was running through sandboxie, mb this is his conflict.
![razorerror](https://cloud.githubusercontent.com/assets/6031470/14216812/73df4f84-f853-11e5-815a-038e86a8e599.jpg)

**Comment by SirGamer** [comment]
Thanks for the report, we'll look into it.

**Comment by Akharote1** [comment]
The Console is not complete yet. I will look into it now. :)

**Comment by Akharote1** [comment]
Fixed in beta 2. Locking
